wezleysherman/TBI-NN-421

- .travis.yml
Implements Travis CI Tests
US 29 Task 73
N/A
N/A
> US29 Task73 Travis CI [In Progress]

- TBI-GUI/src/ui/AlgorithmVisualizerScene.java
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
A page with a graph of data from the algorithm
US57 Task82
Post-condition: swap out dummy data with data from the algorithm.
> Us57 Task82 Algorithm Visualizer Skeleton [Merged]

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/Patient.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
Implements a previous patient selection page as well as some styling that can be implemented throughout the program.
US57 Task98, 99, 100
None
N/A
> US57 Task98 - Previous patient section [Merged]

- TBI-GUI/.classpath
- TBI-GUI/build.gradle
- TBI-GUI/src/tests/PatientClassTests.java
Adds test file for UI and UI elements
US 57 Task 103
N/A
N/A
> Us57 Task103 added test package and added patient class tests

- TBI-GUI/build.gradle
- TBI-GUI/src/tests/AlgorithmVisualizerTests.java
- TBI-GUI/src/tests/AppTests.java
- TBI-GUI/src/ui/AlgorithmVisualizerScene.java
- TBI-GUI/src/ui/App.java
- TBI-GUI/src/ui/LandingScene.java
This tests for App.java and AlgorithmVisualizerScene.java
It also fixes 'gradle test' to run the test cases in the new package
US57 Task105
US29 Task104
N/A
N/A
> US57 Task105 & US29 Task104 added UI Tests for base App and Algorithm Visualizer [Review Requested]

- .travis.yml
- BSSCSFramework/BSSCS_IMG_PROCESSING.py
- BSSCSFramework/data_proc_tests.py
- BSSCSFramework/dicom_test_cases.py
Python unit tests for the data processing package.
US44 Task101
> US44 Task101 Data Processing Unit [Review Requested]

- TBI-GUI/src/tests/AlgorithmVisualizerTests.java
- TBI-GUI/src/ui/AlgorithmVisualizerScene.java
- TBI-GUI/src/ui/App.java
- TBI-GUI/src/ui/CNNVisualizationScene.java
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/LikelyTraumaAreasScene.java
- TBI-GUI/src/ui/NEW_SCENE_REGISTER_INSTRUCTIONS
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Stage Param Removal from UI Pages, StateManager Instructions, Warning fixes/suppressions, Fixed AlgoVis back button, Added try/catch statement to back button so it doesn't break program if implemented incorrectly
polishes up the UI a bit, adds StateManager instructions for new pages, fixes or suppresses many small insignificant warnings, removes the need for a Stage stage param in all scenes.
US57 Task107
PreConditions: code not so good
PostConditions: code slightly more good
> US57 Task107 UI Polish / StateManager updates [Review Requested]

- TBI-GUI/src/ui/App.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/StateManager.java
This adds a patient info scene skeleton and updates the app and statemanager
US30_Task124
N/A
N/A
> US30_Task124 created patient info skeleton [review requested]

- BSSCSFramework/BSSCS_CLASSIFIER.py
Base class for creating a classifier.
US 46 Task 116
None
Nope
> US46 Base implementation for BSSCS Classifier [Review Requested]

- BSSCSFramework/BSSCS_AUTO_ENCODER.py
Base class skeleton for the autoencoder.
Task 112
None
thank u, next
> US47 Base Autoencoder Class [Review Requested]

- TBI-GUI/src/ui/PatientInfoEntryScene.java
Path to view scan page and error handling on empty fields in patient entry scene.
US109 Task 134
N/A
N/A
> Us109 task134 fixed pathing to view scan page

- BSSCSFramework/BSSCS_AUTO_ENCODER.py
- BSSCSFramework/auto_encoder_tests.py
Method to grab middle layer in autoencoder graph and test cases.
US 47 Task 115
> US47 task115 Auto Encoder Partial and Tests [Merged]

- BSSCSFramework/BSSCS_CLASSIFIER.py
Implementations for BSSCS classifier to set optmizier, loss, single layer, full graph
US 46 Tasks 138, 140, 137, 139
No
No
> US46 fully connected implementation [Merged]

- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Home button implemented, fixed constructor for paintScene of PrevPatientScene as well
us109 task123
pre: no home button
post: home button exists and works
> US109 Task123 Home Button on Side Menu

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
Aligns the required indicator tags with the element they should point at perfectly
US109 Task146
None
> US109 Task146 Corrected alignment issue with required tags and removed debug button

- TBI-GUI/src/ui/VerticalSideMenu.java
home button displays warning message when pressed
us109 t145
pre: no warning when return to landing scene
post: warning exists
> US109 Task145: Home Button Warning

- TBI-GUI/src/ui/ScanVisualizerScene.java
makes scan vis scene look like the wireframe for it (file picker button won't be added to the content grid once its in the side menu)
us109 t157
pre: scan vis scene looks messy
post: looks like how we want it to
> US109 Task157: Realign Scan Visualizer to Mimic Wireframes [Review Requested]

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
Fixes styling issues
US111 Tasks 144,142, 143
N/A
N/A
> Us111 Task143 Normalize Styling over landing, patient entry, and scan view pages

- TBI-GUI/src/ui/LandingScene.java
debug set to false, buttons reinstated, buttons event colors changed to be more meaningful
us109 t158
pre: no more debug buttons (annoying to test stuff)
post: debug buttons are back! but only if debug is on!
> US109 Task158: Remake Debug Buttons [Review Requested]

- BSSCSFramework/BSSCS_AUTO_ENCODER.py
All getter and setter methods for the autoencoder class.
User Story 47 - Task 153
> US 47 Task 153 Autoencoder Getter & Setters [Review Requested]

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
implemented tooltips that tell users what the buttons do when hovered over
us110 t122
pre: buttons have no explanation
post: users can tell what buttons will do before pressing them
> US110 Task122: Retroactive Button Tooltips

- TBI-GUI/src/ui/StateManager.java
Makes a minimum size for the app
US111 Task166
N/A
N/A
> US111 Task166 set a minimum size for the app [Review Requested]

- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
The buttons on the left nav now are styled consistently
US111 Task168
N/A
N/A
> US111 Task168 styled the buttons on the left nav [Review Requested]

- BSSCSFramework/retrieval_script/dicom_retrieval_script.py
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
DICOM retrieval script using pyautogui
US130, 111 Tasks 169, 170
N/A
N/A
> Us130 task169 Implement DICOM Retrieval Script

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
PatientInfoScene now has an edit button on the sidebar (edit not implemented yet)
PatientInfoScene initializeScene method now takes a boolean value for editing
"Retrieve" button on PreviousPatientScene now styled, enlarged, and centered
Removed 
US109 Task163
postconditons: I will work on allowing edits on the PatientInfoScene
> US109 Task163 Set up side menu for PatientInfoScene and refactored [Review Requested]

- BSSCSFramework/classifier_tests.py
A base test class with no implementation for the FC framework.
US 53 Task 179
> US53 Task179 fully connected test [Review Requsted]

- TBI-GUI/src/ui/LikelyTraumaAreasScene.java
retroactive document of last sprint
us108 t120
pre: comments weren't done
post: comments are done
> US108 Task120: Likely Trauma Areas Scene Documentation

- BSSCSFramework/CTConverter/DICOM_operations.py
- BSSCSFramework/CTConverter/conversion_test_cases.py
Combines decompression and conversion & implements automatic retry if files are not ready for next step
US31, Task 128
None
None
> US31 Task128 [Review Requested]

- .travis.yml
- BSSCSFramework/BSSCS_CLASSIFIER.py
- BSSCSFramework/classifier_tests.py
Handles all the test cases to verify that the classifier BSSCS framework is working
US53 Task141
> US53 Task141 Classifier Tests [Review Requested]

- TBI-GUI/src/ui/VerticalSideMenu.java
Side menu elements for Likely trauma area scene
US 109, Task 161
N/A
> US109 Task161 Set up side menu for Likely Trauma Areas Scene

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/StateManager.java
most was already done, just filling in some gaps
us108 t121
pre: not much doc
post: little more doc
> US 108 Task 121: Retroactive Documentation for StateManager

- TBI-GUI/build.gradle
- TBI-GUI/src/ui/VerticalSideMenu.java
Allows the program to be run fully using gradle again.
US189 Task 201
N/A
N/A
> US189 Task 201: Add Gradle source directory for resources

- BSSCSFramework/BSSCS_DOCS/conv.html
- BSSCSFramework/BSSCS_DOCS/main.html
HTML based docs for CNN Framework
US 184 Task 194
> US184 Task194 - HTML CNN Docs [Review Requested]

- BSSCSFramework/BSSCS_DOCS/auto.html
HTML Based documentation for the autoencoder.
US 184 Task 195
> US184 Task195 AutoDocs [Review Requested]

- BSSCSFramework/BSSCS_DOCS/auto.html
- BSSCSFramework/BSSCS_DOCS/class.html
- BSSCSFramework/BSSCS_DOCS/main.html
HTML Based docs for the BSSCS classifier
US184 Task196
> Us184 task196 classifier docs [Review Requested]

- TBI-GUI/src/tests/AlgorithmVisualizerTests.java
- TBI-GUI/src/ui/AlgorithmVisualizerScene.java
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/NEW_SCENE_REGISTER_INSTRUCTIONS
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
There is now only one constructor in StateManager. Use the setters and getters to simulate adding more parameters. Also changed the names of sceneIDs to the names of scenes instead of the names of buttons.
US189 Task203
N/A
N/A
> US189 Task203 refactored StateManager constructors [Review Requested]

- TBI-GUI/GUI_DOCS/main.html
- TBI-GUI/GUI_DOCS/viewScanDoc.html
Documentation for View Scan Page in the TBI-GUI
US 183 Task 207
N/A
N/A
> US183 Task207 Create html based documentation for View Scan Page in TBI-GUI

- TBI-GUI/GUI_DOCS/main.html
- TBI-GUI/GUI_DOCS/patientManagementDoc.html
Patient management documentation
US185 task205
none
> US185 Task205 patient management [Review Requested]

- TBI-GUI/src/ui/App.java
- TBI-GUI/src/ui/CNNVisualizationScene.java
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/LikelyTraumaAreasScene.java
- TBI-GUI/src/ui/Patient.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/Style.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Makes styling global in the new Style class.
US189 Task210 
Use Style.java to style things
N/A
> US189 Task210 made styling global [Review Requested]

- BSSCSFramework/BSSCS_DOCS/dicom.html
- BSSCSFramework/BSSCS_DOCS/main.html
Docs for the DICOM importer class
US194 Task209
> US194-Task209-DICOM-Docs [Review Requested]

- BSSCSFramework/BSSCS_DOCS/doc.html
- BSSCSFramework/BSSCS_DOCS/main.html
Docs for the data processing class.
US194 Task187
> Us194 task187 data proc doc [Review Requested]

- TBI-GUI/GUI_DOCS/patientManagementDoc.html
Adds more explanation to encryption
US 185 Task 208
none
none
> US 185 Task 208 [Review Requested]

- BSSCSFramework/BSSCS_DOCS/conversion.html
- BSSCSFramework/BSSCS_DOCS/main.html
conversion docs
us 184 task 211
none
none
> US184 Task211 [Review Requested]

- TBI-GUI/src/ui/ScanVisualizerScene.java
Refactors view scan page to make it more readable
US189 Task 206
N/A
N/A
> US189 Task206 refactor view scan page

- TBI-GUI/GUI_DOCS/patientManagementDoc.html
- TBI-GUI/src/utils/PatientManagement.java
documentation linking for patient management
us 188 doc 219/220
none
none
> US188 Task219/220 adding doc linking [review requested]

- TBI-GUI/GUI_DOCS/algorithmVisualizerDoc.html
docs for algorithm visualizer
US183 Task212
N/A
N/A
> US183 Task212 docs for algorithm visualizer [Review Requested]

- BSSCSFramework/BSSCS_AUTO_ENCODER.py
- BSSCSFramework/BSSCS_CLASSIFIER.py
- BSSCSFramework/BSSCS_CNN.py
- BSSCSFramework/BSSCS_IMG_PROCESSING.py
- BSSCSFramework/DICOMImporter.py
> Us187 task198 cnn docs [Review Requested]

- TBI-GUI/GUI_DOCS/StateManagerDoc.html
statemanager documentation
us183 t221
> US183 Task221: StateManager Documentation

- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/Style.java
Set up proper navigation to view scan page and removed placeholders from PatientInfoScene and removed placeholder list from PreviousPatientScene
US181_Task239,Task240 
You wont be able to see what i did here because I removed the placeholder list, but now ScanVisualizerScene will be reached by clicking on a scan on the PatientInfoScene
> US181_Task239,Task240 

- BSSCSFramework/NN-GUI/App.py
- BSSCSFramework/NN-GUI/setup.txt
- BSSCSFramework/NN-GUI/versions.txt
setup doc for GUI, updates versions, and confirms that NN-GUI supports Python3.6.8
us224 task257
pre: only got it to work with Python3.5
post: confirmed it is working on Python3.6, setup document included in case python/PyQt5 not already on system
> Confirms NN-GUI Supports Python3.6.8

- BSSCSFramework/NN-GUI/App.py
- BSSCSFramework/NN-GUI/versions.txt
Obviously there's still a lot to do, but I'll build off of this since I was learning using this
pulls up a window in python using PyQt5
us224 task243
pre: no work for nn-gui
post: there's a window
> Base Window for NN-GUI

- BSSCSFramework/NN-GUI/App.py
filepicker for .csv files
us224 task245
pre: no filepicker
post: filepicker exists
> US224 Task245: Filepicker for .CSV Files

- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/StateManager.java
You can now add a scan to a patient from the new patient screen. I also fixed an issue with the filechoosers' extensions. Also fixed a bug with getting current time. Also got rid of unused debug code.
US181_Task263
> US181_Task263 adding scan on patient entry scene

- TBI-GUI/src/resources/darkTheme.css
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/StateManager.java
Filtering of previous patient table, dialog box tweaks
US180 Task264, 265
N/A
N/A
> Us180 task265, 264 Filtering previous patient table [Review Requested]

- BSSCSFramework/CTConverter/DICOM_operations.py
- BSSCSFramework/DICOMImporter.py
- BSSCSFramework/UNET_Data.py
- BSSCSFramework/UNET_Graph.py
- BSSCSFramework/UNET_Setup_Script.py
- BSSCSFramework/test_csv.csv
- Data-Processing-Scripts/DICOMAnonimizer.py
UNET Architecture and data processing
US222 and corresponding Tasks
> US222 unet implementation [Review Requested]

- TBI-GUI/src/utils/Scan.java
fixes scan import
191/289
none
none
> fixed scan import

- TBI-GUI/src/tests/PatientClassTests.java
- TBI-GUI/src/utils/Patient.java
- TBI-GUI/src/utils/Scan.java
removes unnecessary redundancy in patient class and properly sorts scans by date
us 191 tasks 289/297
none
n/a
> patient cleanup and scan sorting

- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
You can delete a patient via the "delete patient" button on the PatientInfoScene. There is a new method in StateManager to ask the user a question. This was used to redo the "Home" button popup. Also, the VerticalSideMenu was refactored to have a more consistent coding style.
US36_Task295
> US36_Task295 added delete patient button and refactored VerticalSideMenu

- TBI-GUI/src/resources/darkTheme.css
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/StateManager.java
Switches the styling of the landing page and the patient entry page to use stylesheet
US268 Task 298
N/A
N/A
> US268_Task298 Landing page and Patient info entry page switch to stylesheet [Review Requested]

- TBI-GUI/GUI_DOCS/main.html
- TBI-GUI/GUI_DOCS/patientDoc.html
Patient documentation
191/300
none
n/a
> Us191 task300

- TBI-GUI/src/resources/darkTheme.css
- TBI-GUI/src/ui/CNNVisualizationScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Styles elements using style sheet instead of style class
US268 Task 310
N/A
N/A
> Us268 task310 Style mulple elements in the ui using the stylesheet

- BSSCSFramework/NN-GUI/App.py
The three button listed in the title (not their functions yet)
us276 tasks 311, 312, 314
pre: buttons didnt exist
post: they exist, but with no functions yet
> US276 Tasks311,312,314: Load .csv Button, Load Image Folder Button, Train Button

- TBI-GUI/.gitignore
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Adds an error log function. Refactored the makeDialog function that printed the error to be makeError and take in the whole error instead of a string. this will cut down on reused code of formatting the stack trace. 
US50_Task286
> US50_Task286 made an error log

- .travis.yml
- BSSCSFramework/BSSCS_DATA_PROCESSOR.py
- BSSCSFramework/UNET_Data.py
- BSSCSFramework/UNET_Setup_Script.py
- BSSCSFramework/data_proc_tests.py
> US278-Task285-Base-Data [Review Me!]

- BSSCSFramework/NN-GUI/App.py
Still need to be implemented / find a better method for using them, but they seem okay with maybe having a text field underneath to show the exact value
us276 task313
pre: no sliders
post: sliders
> Sliders added for batch and iterations

- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Tried to make the error throwing more consistent. And tried to not have an entire method be in a try catch and just put the part that would cause the error in the try block.
US50_Task282
> US50_Task282 made error throwing more consistent

- TBI-GUI/src/ui/ScanVisualizerScene.java
Refactors View Scan page
US270 Task 294
N/A
N/A
> US270 Task294 Refactor view scan page and remove unused elements [Review Requested]

- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Better error messages for errors in the Java UI
US50_Task324
> US50_Task324 added error messages to catch blocks

- TBI-GUI/GUI_DOCS/patientDoc.html
- TBI-GUI/src/tests/PatientClassTests.java
- TBI-GUI/src/tests/PatientManagementTest.java
- TBI-GUI/src/utils/Patient.java
> Us191 task301 [review requested]

- BSSCSFramework/NN-GUI/App.py
stores values from sliders
us276 t315
pre: slider values not stored or displayed
post: the opposite of that
> US276 Task315: Storing Batch/Iter Values from Sliders

- TBI-GUI/src/ui/AlgorithmVisualizerScene.java
- TBI-GUI/src/ui/CNNVisualizationScene.java
- TBI-GUI/src/ui/LandingScene.java
- TBI-GUI/src/ui/LikelyTraumaAreasScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/TopMenuBar.java
Adds a top menu bar
US338_Task346/360
The buttons in the drop downs are not functional yet
> US338_Task346/360 added top menu bar

- TBI-GUI/src/resources/darkTheme.css
- TBI-GUI/src/ui/TopMenuBar.java
Shortcuts to Home, New Patient, and Patient List are functional. Menubar is now styled.
US338_Task358/359/364
> US338_Task358/359/364 made shortcuts functional and styled menubar

- BSSCSFramework/NN-GUI/App.py
loads in all images from a selected directory
us341 t347
pre: not implements
post: loads img files
> US341 Task 347: Load in Image Folder

- BSSCSFramework/NN-GUI/App.py
error checking for filepickers and changing slider values
us341 t368,374
pre: not implemented
post: implemented :)
> US341 Task368&374

- BSSCSFramework/BSSCS_DOCS/UNET_Data.html
- BSSCSFramework/BSSCS_DOCS/UNET_Graph.html
- BSSCSFramework/BSSCS_DOCS/main.html
> Us335 unet docs [Review]

- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
If no date is selected when adding a scan, it will default to the current day.
US269_Task343
> US269_Task343 Date defaults to today if no date selected

- BSSCSFramework/NN-GUI/App.py
filenames instead of filepaths
us341 task381
pre: filepaths
post: filenames
> US341 Task381: Change Filepaths into Filenames

- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
You can now add multiple files when making or editing a patient
US269_Task345
> US269_Task345 adding multiple scans at once

- TBI-GUI/src/utils/ThemeManagement.java
> adding theme management

- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
You can now edit notes and date of a scan in scan visualizer. I also fixed an issue with deleting a scan from that page.
US269_Task344
> US269_Task344 edit scan

- BSSCSFramework/UNET_Data.py
- BSSCSFramework/UNET_Graph.py
- BSSCSFramework/UNET_Setup_Script.py
> US337 unet labels [Review]

- BSSCSFramework/NN-GUI/App.py
The whole Tensorboard Section of the GUI
us341 t384,387,385,386
pre: no tensorboard section
post: it exists
> US341 Task384: Tensorboard Section

- TBI-GUI/.matplotlib/fontlist-v300.json
- TBI-GUI/build.gradle
- TBI-GUI/build.number
- TBI-GUI/src/python/NiftiViewer.py
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
Makes niftviewer launch from both gradle and eclipse.
US342/340 Task 388/361
N/A
N/A
> US342/340_Task388/361 Make running nifti viewer from gradle or eclipse run

- TBI-GUI/build.number
- TBI-GUI/src/python/NiftiViewer.py
- TBI-GUI/src/ui/StateManager.java
Make it so the niftiviewer takes file input from the main GUI
US 390 Tasks 411
N/A
N/A
> US390 Tasks411 Make it so the niftiviewer takes file input from the main GUI

- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/ThemeCreationScene.java
- TBI-GUI/src/ui/TopMenuBar.java
Added ThemeCreationTheme and provided a link to it in Preferences
US391_Task401
> US391_Task401 Added ThemeCreationTheme and provided a link to it in Preferences

- TBI-GUI/src/ui/ThemeCreationScene.java
list out most of the elements on the theme creator
US391_Task403
> US391_Task403 list out all the elements on the theme creator

- TBI-GUI/build.number
- TBI-GUI/src/python/NiftiViewer.py
- TBI-GUI/src/ui/LikelyTraumaAreasScene.java
- TBI-GUI/src/ui/StateManager.java
Updates UI on opening of the niftiviewer, sends filepath more efficiently
US390 Tasks 413,421
N/A
N/A
> US390_Task413,421 Send filepath more efficiently and test updating UI on open

- TBI-GUI/src/resources/themes/darkTheme.css
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ThemeCreationScene.java
The theme is now previewed when changing colors. Also a button for save is added, but doesn't work yet.
US391_Task406
> US391_Task406 Theme Preview

- TBI-GUI/src/ui/LikelyTraumaAreasScene.java
- TBI-GUI/src/ui/LoadingScene.java
Create animation for opening the niftiviewer
US390 Task 407
N/A
N/A
> US390 Task407 Create animation for opening the niftiviewer

- TBI-GUI/src/resources/themes/darkTheme.css
- TBI-GUI/src/ui/ThemeCreationScene.java
Saves themes to a css file when done
US391_Task402
> US391_Task402 saving themes to css files

- TBI-GUI/build.number
- TBI-GUI/src/python/NiftiViewer.py
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
Add loading screen and opening of niftiviewer to the normal flow of the program
US390 Task 430
N/A
N/A
> US390_Task430 Add loading screen and opening of niftiviewer to the normal flow of the program

- TBI-GUI/src/resources/themes/darkTheme.css
- TBI-GUI/src/ui/ThemeCreationScene.java
- TBI-GUI/src/ui/TopMenuBar.java
- TBI-GUI/src/ui/VerticalSideMenu.java
ThemeCreationScene has scroll bars
ScrollBars are styled
ColorPickers are styled
Message pops up if trying to load the theme already loaded
US391_Task404&428
> US391_Task404&428 add scroll bar and dialog messages to themes

- TBI-GUI/src/resources/themes/Dark.css
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/ThemeCreationScene.java
- TBI-GUI/src/ui/TopMenuBar.java
Imports themes and puts them in the preferences drop down. Css refactored to be shorter. Refactored the way css is loaded. It now loads from an absolute path instead of a relative path due to issues when adding a new theme and resources not being updated at run time.  
US391 Task405/438
> US391 Task405/438 Imports themes and css refactored

- TBI-GUI/src/ui/ScanVisualizerScene.java
Add error checking to opening the niftiviewer
US390 Task 434
N/A
N/A
> Us390 task434 Add error checking to opening the niftiviewer

- BSSCSFramework/NN-GUI/NNGUI.py
> tensorboard instance

- TBI-GUI/build.number
- TBI-GUI/src/resources/themes/Contrast.css
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/ThemeCreationScene.java
Adds a high contrast theme
US375_Task451
> US375_Task451 High Contrast Theme

- TBI-GUI/GUI_DOCS/main.html
- TBI-GUI/GUI_DOCS/themeCreatorDoc.html
Documentation for the theme creator
US439_Task450
> US439_Task450 Documentation for the theme creator

- TBI-GUI/GUI_DOCS/NiftiViewerDoc.html
- TBI-GUI/GUI_DOCS/main.html
Add documentation for the niftiviewer
us440 task458
N/A
N/A
> US440_Task458 Add documentation for the niftiviewer

- TBI-GUI/src/python/NiftiViewer.py
Add ability for niftiviewer to open image files such as png or jpeg
US444 Task 464
N/A
N/A
> US444_Task464 Add ability for niftiviewer to open image files such as png or jpeg

- TBI-GUI/src/python/NiftiViewer.py
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
Made it so scans take png and jpeg images as well as removed a couple errors
US444 Task 468
N/A
N/A
> Us444 task468 Made it so scans take png and jpeg image

- TBI-GUI/GUI_DOCS/NiftiViewerDoc.html
- TBI-GUI/src/ui/ScanVisualizerScene.java
Add a timer to opening the niftiviewer
US459 Task 465
N/A
N/A
> Us459 task465 Add a timer to opening the niftiviewer

- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/utils/Holder.java
Picture of patient now displayed and notes area is sized larger.
US40_Task452
> US40_Task452 display picture for patient

- TBI-GUI/src/ui/VerticalSideMenu.java
Make editing of notes for scans more intuitive
US459 Task 474
N/A
N/A
> Us459 task474 Make editing of notes for scans more intuitive

- TBI-GUI/src/resources/themes/PCH.css
> US375_Task460 PCH Theme

- TBI-GUI/src/ui/AlgorithmVisualizerScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Make scan switching buttons function, add double clicking to tables cleanup imports, remove unnecessary code
US459 Task 485
N/A
N/A
> Us459 task485 Make scan switching buttons function, add double clicking to tables

- TBI-GUI/src/ui/LoadingScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
Display percentage complete in scan vis page
US 479 Task 500 + 515
N/A
N/A
> Us479 task500/515  Display percentage complete in scan vis page

- TBI-GUI/build.number
- TBI-GUI/src/tests/PatientClassTests.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
- TBI-GUI/src/utils/NNUtils.java
- TBI-GUI/src/utils/Patient.java
- TBI-GUI/src/utils/Scan.java
Scan object now has 2 files associated with it. 
Patient object now only has 1 scan list. 
US477_Task522
> US477_Task522 refactor scan and patient object

- TBI-GUI/.classpath
- TBI-GUI/build.number
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
Add ability to add scan from patient info scene
US480 Task 501
N/A
N/A
> Us480 task501 Add ability to add scan from patient info scene

- BSSCSFramework/NN-GUI/NNGUI.py
title
title
pre: not title
post: title
> Us481 t492,493,494,495

- TBI-GUI/src/ui/ScanVisualizerScene.java
There is now a button to view raw scan
US477_Task523
> US477_Task523 added raw scan to view

- NN-GUI.bat
- README.md
- TBI-GUI.txt
- TBI-GUI/GUI_DOCS/NiftiViewerDoc.html
- TBI-GUI/build.number
Adds installation info to the README, a bat file to launch the NN-GUI, and fixed a spelling error in the docs.
US477_Task517
> US477_Task517 README

- TBI-GUI/build.number
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/VerticalSideMenu.java
- TBI-GUI/src/utils/Patient.java
- TBI-GUI/src/utils/Scan.java
Make patient entry page more intuitive and remove null text from notes
US480 Tasks516, 520
N/A
> Us480 task516 Make patient entry page more intuitive and remove null text from notes

- BSSCSFramework/NN-GUI/Customizations.py
- BSSCSFramework/NN-GUI/NNGUI.py
title
title
pre: not title
post: title
> Us481 t496,497,498

- TBI-GUI/build.number
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/VerticalSideMenu.java
> Text length fixes

- NN-GUI.bat
- TBI-GUI.bat
> Packaging Stuff

- README.md
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/utils/Patient.java
> fixed scene issue and added links to readme

- README.md
- TBI-GUI/build.number
- TBI-GUI/src/tests/PatientClassTests.java
- TBI-GUI/src/tests/PatientManagementTest.java
- TBI-GUI/src/tests/ThemeTests.java
- TBI-GUI/src/ui/App.java
- TBI-GUI/src/ui/LoadingScene.java
- TBI-GUI/src/ui/PatientInfoEntryScene.java
- TBI-GUI/src/ui/PatientInfoScene.java
- TBI-GUI/src/ui/PreviousPatientScene.java
- TBI-GUI/src/ui/ScanVisualizerScene.java
- TBI-GUI/src/ui/StateManager.java
- TBI-GUI/src/ui/ThemeCreationScene.java
- TBI-GUI/src/ui/TopMenuBar.java
- TBI-GUI/src/ui/VerticalSideMenu.java
- TBI-GUI/src/utils/EncryptionUtils.java
- TBI-GUI/src/utils/Info.java
- TBI-GUI/src/utils/InfoEntry.java
- TBI-GUI/src/utils/NNUtils.java
- TBI-GUI/src/utils/Patient.java
- TBI-GUI/src/utils/PatientEntry.java
- TBI-GUI/src/utils/PatientManagement.java
- TBI-GUI/src/utils/Scan.java
- TBI-GUI/src/utils/ThemeManagement.java
- TBI-GUI/src/utils/User.java
- TBI-GUI/src/utils/UserEntry.java
- TBI-GUI/src/utils/UserManagement.java
See commit messages
N/A
N/A
N/A
> Ty Final Changes

- TBI-GUI/src/ui/StateManager.java
> Removed broken timer
